version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/logs:/app/logs
      - ./backend/uploads:/app/uploads
    environment:
      - DATABASE_URL=sqlite:///./sar_missions.db
    depends_on:
      - db
    networks:
      - sar-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - VITE_API_URL=http://localhost:8000/api/v1
    depends_on:
      - backend
    networks:
      - sar-network

  db:
    image: sqlite:3
    volumes:
      - ./backend/sar_missions.db:/data/sar_missions.db
    networks:
      - sar-network

networks:
  sar-network:
    driver: bridge