apiVersion: v1
kind: Namespace
metadata:
  name: sar-drone-system
  labels:
    name: sar-drone-system
    app.kubernetes.io/name: sar-drone-system
    app.kubernetes.io/version: "2.0.0"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: sar-drone-quota
  namespace: sar-drone-system
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    pods: "20"
    services: "10"
    persistentvolumeclaims: "10"
