name: CI - Backend smoke tests

on:
  push:
    branches:
      - refactor/**
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping || exit 1"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements_core_runtime.txt

      - name: Compile backend
        run: python -m compileall -q backend/

      - name: Run smoke tests
        env:
          PYTEST_ADDOPTS: "--maxfail=1 --disable-warnings"
        run: |
          pytest backend/tests -q


